In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../dataset/Alphabet data/A_Z Handwritten Data.csv')

In [5]:
df

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.639,0.640,0.641,0.642,0.643,0.644,0.645,0.646,0.647,0.648
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372445,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372446,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372447,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372448,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372449,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
X = df.drop('0', axis=1)
y = df['0']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=19)

In [8]:
X_train.shape

(297960, 784)

In [9]:
X_train = X_train/255
X_test = X_test/255

In [10]:
from tensorflow.keras.utils import to_categorical

In [12]:
y_train = to_categorical(y_train, num_classes=26)
y_test = to_categorical(y_test, num_classes=26)

In [13]:
X_train = X_train.values.reshape(-1, 28, 28, 1)
X_test = X_test.values.reshape(-1, 28, 28, 1)

In [14]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten
from tensorflow.keras.models import Sequential

In [18]:
model = Sequential()
model.add(Conv2D(16,(3,3),activation='relu', input_shape=(28,28,1)))
model.add(MaxPool2D())
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D())
model.add(Flatten())
model.add(Dense(26,activation='softmax'))

model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_2 (Conv2D)           (None, 26, 26, 16)        160

 max_pooling2d_2 (MaxPooling  (None, 13, 13, 16)       0
 2D)

 conv2d_3 (Conv2D)           (None, 11, 11, 32)        4640

 max_pooling2d_3 (MaxPooling  (None, 5, 5, 32)         0
 2D)

 flatten_1 (Flatten)         (None, 800)               0

 dense_1 (Dense)             (None, 26)                20826

=================================================================
Total params: 25,626
Trainable params: 25,626
Non-trainable params: 0
_________________________________________________________________

In [22]:
hist1 = model.fit(X_train, y_train, batch_size=64, epochs=10)

Epoch 1/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0266 - accuracy: 0.9933
Epoch 2/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0261 - accuracy: 0.9933
Epoch 3/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0257 - accuracy: 0.9935
Epoch 4/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0256 - accuracy: 0.9934
Epoch 5/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0248 - accuracy: 0.9936
Epoch 6/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0243 - accuracy: 0.9938
Epoch 7/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0240 - accuracy: 0.9938
Epoch 8/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0234 - accuracy: 0.9940
Epoch 9/10
4656/4656 [==============================] - 100s 21ms/step - loss: 0.0233 - accuracy: 0.9941
Epoch 10/10
4656/4656 [==============================] - 101s 22ms/step - loss: 0.0227 - accuracy: 0.9942

In [24]:
import os, cv2

In [27]:
os.listdir('../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/')

['A.jpg',
 'B.jpg',
 'C.jpg',
 'D.jpg',
 'E.jpg',
 'F.jpg',
 'G.jpg',
 'H.jpg',
 'I.jpg',
 'J.jpg',
 'K.jpg',
 'L.jpg',
 'M.jpg',
 'N.jpg',
 'O.jpg',
 'P.jpg',
 'Q.jpg',
 'R.jpg',
 'S.jpg',
 'T.jpg',
 'U.jpg',
 'V.jpg',
 'W.jpg',
 'X.jpg',
 'Y.jpg',
 'Z.jpg']

In [28]:
A = cv2.imread('../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/'+'A.jpg', 0)

In [29]:
def predict(path):
    A = cv2.imread(path, 0)
    A = cv2.resize(A,(28,28))
    A = A.reshape(-1, 28, 28, 1)/255
    return model.predict_on_batch(A).argmax()

In [30]:
filenames = os.listdir('../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/')
for i in filenames:
    print('../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/'+i)

../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/A.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/B.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/C.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/D.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/E.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/F.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/G.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/H.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/I.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/J.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/K.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/L.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/M.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/N.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/O.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/P.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/Q.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/R.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/S.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/T.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/U.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/V.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/W.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/X.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/Y.jpg
../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/Z.jpg

In [34]:
for i in filenames:
    Alphabet = predict('../../DSML19/dataset/Alphabet data/Alphabets A-Z/Alphabets A-Z/'+i)
    print(i, '\t', Alphabet)

A.jpg 	 0
B.jpg 	 1
C.jpg 	 2
D.jpg 	 3
E.jpg 	 11
F.jpg 	 11
G.jpg 	 4
H.jpg 	 7
I.jpg 	 8
J.jpg 	 9
K.jpg 	 10
L.jpg 	 9
M.jpg 	 12
N.jpg 	 13
O.jpg 	 22
P.jpg 	 15
Q.jpg 	 16
R.jpg 	 17
S.jpg 	 25
T.jpg 	 19
U.jpg 	 20
V.jpg 	 24
W.jpg 	 19
X.jpg 	 23
Y.jpg 	 24
Z.jpg 	 5